# https://chaos-mesh.org/docs/simulate-network-chaos-on-kubernetes/
apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-partition
  namespace: chaos-tests
  labels:
    chaos-mesh: network
    network: partition
spec:
  action: partition
  mode: all
  duration: 60s
  selector:
    namespaces:
      - simple-k8s
    labelSelectors:
      'app': 'simple-k8s-frontend'
  direction: both
  target:
    mode: all
    selector:
      namespaces:
        - simple-k8s
      labelSelectors:
        'app': 'simple-k8s-backend'