# https://chaos-mesh.org/docs/simulate-heavy-stress-on-kubernetes/
apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: stress-cpu
  namespace: chaos-tests
  labels:
    chaos-mesh: stress
    stress: cpu
spec:
  mode: one
  duration: 60s
  selector:
    namespaces:
    - simple-k8s
    labelSelectors:
      'app': 'simple-k8s-backend'
  stressors:
    cpu:
      workers: 4
      load: '80'