apiVersion: v1
kind: Service
metadata:
  name: simple-k8s-backend-service
  namespace: simple-k8s
  labels:
    svc: simple-k8s-backend-service
spec:
  selector:
    app: simple-k8s-backend
  ports:
  - port: 3000
    targetPort: 3000
