# https://chaos-mesh.org/docs/simulate-pod-chaos-on-kubernetes/
apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: pod-failure
  namespace: chaos-tests
  labels:
    chaos-mesh: pod
    pod: failure
spec:
  action: pod-failure
  mode: one
  duration: '60s'
  selector:
    namespaces:
    - simple-k8s
    labelSelectors:
      'app': 'simple-k8s-backend'
      